"""Add BFS models

Revision ID: 0cfe1ca1afa1
Revises: dd19331cbd0e
Create Date: 2025-12-22 16:31:15.734382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0cfe1ca1afa1'
down_revision = 'dd19331cbd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop table only if it exists (SQLite doesn't support IF EXISTS directly in SQLAlchemy)
    # Removed: op.drop_table('binary_search_tree_operation')
    
    with op.batch_alter_table('bfs_operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segments', sa.JSON(), nullable=True))
        batch_op.drop_column('distance_km')
        batch_op.drop_column('visited_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bfs_operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_order', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.FLOAT(), nullable=True))
        batch_op.drop_column('segments')

    op.create_table('binary_search_tree_operation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tree_data', sqlite.JSON(), nullable=True),
    sa.Column('next_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
