"""add binary search tree operation

Revision ID: a0c4bca6a781
Revises: 0cfe1ca1afa1
Create Date: 2026-01-18 09:07:14.949290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c4bca6a781'
down_revision = '0cfe1ca1afa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binary_search_tree_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_data', sa.JSON(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binary_search_tree_operation')
    # ### end Alembic commands ###
