"""Add BFS models for train stations

Revision ID: dd19331cbd0e
Revises: 93184487789b
Create Date: 2025-12-22 16:02:22.438629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'dd19331cbd0e'
down_revision = '93184487789b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bfs_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_station', sa.String(length=100), nullable=True),
    sa.Column('end_station', sa.String(length=100), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('visited_order', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=True),
    sa.Column('stations_list', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('binary_search_tree_operation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binary_search_tree_operation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tree_data', sqlite.JSON(), nullable=True),
    sa.Column('next_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('train_graph')
    op.drop_table('bfs_operation')
    # ### end Alembic commands ###
